# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '4.6', '6.0' ]
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      if: matrix.dotnet-version == '6.0'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Setup MSBuild
      if: matrix.dotnet-version == '4.6'
      uses: microsoft/setup-msbuild@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        if [ "${{ matrix.dotnet-version }}" == "4.6" ]; then
          msbuild /p:Configuration=Release
        else
          dotnet build --no-restore
        fi
    - name: Generate Artifacts
      run: .\PrepareRelease.bat
    - name: Upload V5 Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Betterloid V5
        path: Betterloid5.zip
    - name: Upload V6 Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Betterloid V6
        path: Betterloid6.zip
