name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild and .NET
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet msbuild /p:Configuration=Release /p:TargetFrameworks="net46;net6.0"
    - name: Generate Artifacts
      run: .\PrepareRelease.bat
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Betterloid Artifacts
        path: Betterloid.zip
