name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild and .NET
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: latest
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Generate Artifacts
      run: .\PrepareRelease.bat
    - name: Upload Betterloid 5 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Betterloid5.zip
        path: Betterloid5.zip
    - name: Upload Betterloid 6 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Betterloid6.zip
        path: Betterloid6.zip
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download Betterloid 5 Artifact
      uses: actions/download-artifact@v4
      with:
        name: Betterloid5.zip
        path: .
    - name: Download Betterloid 6 Artifact
      uses: actions/download-artifact@v4
      with:
        name: Betterloid6.zip
        path: .
    - name: Get short commit hash
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.SHORT_SHA }}
        release_name: Betterloid ${{ env.SHORT_SHA }}
        draft: false
        prerelease: true
    - name: Upload Betterloid 5 Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Betterloid5.zip
        asset_name: Betterloid5.zip
        asset_content_type: application/zip
    - name: Upload Betterloid 6 Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Betterloid6.zip
        asset_name: Betterloid6.zip
        asset_content_type: application/zip
